# Generated by Django 5.0.1 on 2025-09-11 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aldeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran_aldeia', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran_feeder', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Munisipiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munisipiu', models.CharField(blank=True, max_length=25, null=True)),
                ('kodigu', models.CharField(blank=True, max_length=25, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('inline_color', models.CharField(blank=True, max_length=7, null=True)),
                ('outline_color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(blank=True, max_length=50, null=True)),
                ('id_identidade', models.CharField(blank=True, max_length=11, null=True)),
                ('naran_kompanhia', models.CharField(blank=True, max_length=30)),
                ('kategoria_kliente', models.CharField(choices=[('rezidensial', 'Rezidensial'), ('komersial', 'Komersial'), ('sosial', 'Sosial'), ('governu', 'Governu'), ('agensia internasional', 'Agensia Internasional')], max_length=25)),
                ('hela_fatin', models.CharField(blank=True, max_length=25, null=True)),
                ('kordinat', models.CharField(blank=True, max_length=100, null=True)),
                ('no_tlf', models.CharField(blank=True, max_length=12, null=True)),
                ('data_rejistu', models.DateField(blank=True, null=True)),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aldeia')),
            ],
        ),
        migrations.CreateModel(
            name='Imajen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Postu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postu', models.CharField(blank=True, max_length=15, null=True)),
                ('munisipiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.munisipiu')),
            ],
        ),
        migrations.CreateModel(
            name='RejistuKontadorFoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran_kliente', models.CharField(blank=True, max_length=30, null=True)),
                ('numeru', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('data_pedidu', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aldeia')),
            ],
        ),
        migrations.CreateModel(
            name='Selu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montante', models.FloatField()),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Suku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suku', models.CharField(blank=True, max_length=25, null=True)),
                ('postu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.postu')),
            ],
        ),
        migrations.AddField(
            model_name='aldeia',
            name='suku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.suku'),
        ),
        migrations.CreateModel(
            name='Tekniku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tekniku', models.CharField(blank=True, max_length=10, null=True)),
                ('naran', models.CharField(blank=True, max_length=50, null=True)),
                ('enderesu', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('no_tlf', models.CharField(blank=True, max_length=8, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipu_ligasaun', models.CharField(blank=True, choices=[('monofasico', 'Monofasico'), ('trifasico', 'Trifasico')], max_length=10, null=True)),
                ('feeder', models.CharField(blank=True, max_length=3, null=True)),
                ('nu_trafo', models.CharField(blank=True, max_length=5, null=True)),
                ('data_survey', models.DateField(blank=True, null=True)),
                ('deskrisaun_instalasaun', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('tekniku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tekniku')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tekniku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tekniku'),
        ),
        migrations.CreateModel(
            name='Trafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kordinat', models.TextField()),
                ('zona', models.CharField(blank=True, max_length=20, null=True)),
                ('feeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_kontador', models.CharField(blank=True, max_length=11, null=True)),
                ('phase', models.CharField(blank=True, choices=[('mono phase', 'Mono Phase'), ('three phase', 'Three Phase')], max_length=15, null=True)),
                ('dijuntor_jeral', models.IntegerField(blank=True, null=True)),
                ('medida_kabu', models.CharField(blank=True, max_length=10, null=True)),
                ('numeru_trafo', models.CharField(blank=True, max_length=10, null=True)),
                ('numeru_pole', models.CharField(blank=True, max_length=10, null=True)),
                ('konta_tuan', models.CharField(blank=True, max_length=11, null=True)),
                ('ligasaun_arde', models.CharField(blank=True, choices=[('iha', 'Iha'), ('laiha', 'Laiha')], max_length=10, null=True)),
                ('kordinat', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('tekniku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tekniku')),
                ('trafo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trafo')),
            ],
        ),
    ]
