# Generated by Django 5.0.1 on 2025-10-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente_created_at_cliente_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aldeia',
            name='suku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aldeias', to='app.suku'),
        ),
        migrations.AlterField(
            model_name='postu',
            name='munisipiu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postus', to='app.munisipiu'),
        ),
        migrations.AlterField(
            model_name='suku',
            name='postu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sukus', to='app.postu'),
        ),
    ]
