# Generated by Django 5.0.1 on 2025-10-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aldeia_suku_alter_postu_munisipiu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='munisipiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.munisipiu'),
        ),
    ]
