# Generated by Django 5.0.1 on 2025-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feeder_munisipiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='deskrisaun_zona',
            field=models.TextField(blank=True, null=True),
        ),
    ]
