# Generated by Django 5.0.1 on 2025-10-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feeder_deskrisaun_zona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contador',
            old_name='dijuntor_jeral',
            new_name='disjuntor_jeral',
        ),
    ]
