# Generated by Django 5.0.1 on 2025-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_dijuntor_jeral_contador_disjuntor_jeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='marka',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
