# Generated by Django 5.0.1 on 2025-10-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feeder_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imajen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imajen/'),
        ),
    ]
