# Generated by Django 5.0.1 on 2025-10-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_imajen_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='kordinat',
        ),
    ]
