# Generated by Django 5.0.6 on 2026-07-29 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_cliente_kordinat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kodigu_keixa",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "kategoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mate_lampu", "Mati Lampu (Blackout)"),
                            ("trafo_aat", "Trafo Bermasalah"),
                            ("kontador_aat", "Meteran Rusak"),
                            ("seluk", "Lain-lain"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("deskrisaun", models.TextField(blank=True, null=True)),
                ("data_keixa", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente (Menunggu)"),
                            ("prosesu", "Iha Prosesu (Sedang Dikerjakan)"),
                            ("remata", "Remata (Selesai)"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="keixa/")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.cliente",
                    ),
                ),
                (
                    "tekniku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.tekniku",
                    ),
                ),
            ],
        ),
    ]
